M48
; DRILL file {KiCad 8.0.2} date 2024-06-19T11:28:39-0400
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-06-19T11:28:39-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.2
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0118
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T2C0.0295
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0354
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T4C0.0394
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T5C0.0512
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T6C0.0591
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T7C0.0709
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T8C0.0984
%
G90
G05
T1
X7.1299Y-2.4882
T2
X7.6142Y-3.4961
X7.9646Y-3.4764
T3
X7.1811Y-2.3346
X7.2598Y-2.3346
X7.3386Y-2.3346
T4
X8.6575Y-3.374
X8.6575Y-3.474
T5
X7.8976Y-3.3819
T6
X7.0984Y-2.3346
X7.4213Y-2.3346
T7
X7.9016Y-3.6693
X7.9016Y-4.1205
T8
X3.8583Y-5.248
M30
